openapi: 3.0.0
info:
  title: Configuration Property Update API
  description: API to update configuration properties.
  version: 1.0.0
servers:
  - url: https://api.example.com
    description: Production server
paths:
  /update-property:
    get:
      summary: Update a configuration property
      responses:
        '200':
          description: Configuration property updated successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Configuration property updated successfully.
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid request parameters.
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: An unexpected error occurred.
components:
  securitySchemes:
    clientIdHeader:
      type: apiKey
      in: header
      name: X-Client-Id
security:
  - clientIdHeader: []